### ISSUE TITLE
BubbleParent property not working with scrollview on SDK 7.4.0 GA

### ISSUE THREAD

**Issue by suhaskumbhar** [appcelerator/titanium_mobile#10325]
**Describe the bug**
bubbleParent property on view not working on latest SDK 7.4.0 GA (XCODE 10).

We have signature drawing panel inside of scrollview. To stop scrolling on outer scrollview while drawing , we have put bubbleParent="false" on signature drawing webview.
Until SDK 7.3.1 GA and XCODE 9.2 , signature drawing was working fine.
But with SDK 7.4.0 GA and XCODE 10, the outer scrollview is scrolling .
Attaching videos below - One working with SDK 7.3.1 and one broken with SDK 7.4.0

**To Reproduce**
Steps to reproduce the behavior, e.g.:
1. Build app on SDK 7.4.0
2. Try drawing a signature in white box
3. See entire page scrolls. Page shouldn't scroll while signing.

**Expected behavior**
As Sign widget has bubbleParent="false", scrolling should not happen on parent view. It works as expected on SDK 7.3.1 GA. But breaks on SDK 7.4.0 GA

**Environment**
Titanium SDK version: SDK 7.4.0 GA
CLI version: 7.0.6

**Logs**:
Videos attached. 

[Sign drawing scroll issue videos.zip](https://github.com/appcelerator/titanium_mobile/files/2394234/Sign.drawing.scroll.issue.videos.zip)

(Attach by dragging into this issue)

**Comment by hansemannn** [comment]
Thanks for the report! It seems like a breaking change in iOS 12+. @topener can you move this to JIRA?

**Comment by m1ga** [comment]
@hansemannn https://jira.appcelerator.org/browse/AC-5893

**Comment by hansemannn** [comment]
Thanks! Closing to keep in sync there.
