### ISSUE TITLE
App icon went back to default after upgrading to SDK 8.0.0.GA

### ISSUE THREAD

**Issue by AbdullahFaqeir** [appcelerator/titanium_mobile#10801]
**Describe the bug**
After upgrading to Titanium SDK 8.0.0.GA from 7.5.0.1GA the app icon on android went back to titaniums default icon when running on Android.

**Expected behavior**
The app should use the icon provided.

**Environment**
Titanium CLI
  CLI Version                 = 5.1.1
Titanium SDK
  SDK Version                 = 8.0.0.GA

**Comment by m1ga** [comment]
already closed and merged into 8.0.1: https://github.com/appcelerator/titanium_mobile/pull/10780
it is just a one-line fix for the `_build.js` so you can apply it to your 8.0.0 installation too

**Comment by ewanharris** [comment]
Yup Michael is right, this issue was fixed in #10780 and #10781. You are be able to get the latest 8.0.1 CI build by running `appc ti sdk install -b 8_0_X -d`

**Comment by AbdullahFaqeir** [comment]
Thanks you so much guys.
