### ISSUE TITLE
Compilation for iOS fails if the file system is case-sensitive

### ISSUE THREAD

**Issue by TheVisitorXX** [appcelerator/titanium_mobile#10825]
Problem:

If you try to compile for iOS with the latest SDK 8 release, you will get a BUILD FAILED error during xcodebuild if your filesystem is case sensitive, because Xcode can't build the TitaniumKit module.

This happens because of wrong or not uniform naming of the 'Webcolor' file(s) / references. Sometimes it's called 'Webcolor', sometimes it's called 'WebColor'. 

Expected result:

All occurrences should be renamed to 'WebColor' on all places to make it similar to all other files and to get a uniform file naming convention - and to prevent possible issues with case sensitive file systems in the future.

System used:

macOS Mojave 10.14.3
Titanium SDK 8.0.0.GA 
Xcode 10.2

**Comment by sgtcoolguy** [comment]
Thanks for the report @TheVisitorXX - I just pushed a fix for this to the master branch.
