### ISSUE TITLE
WKWebView Not Allowing OAuth Redirect Process

### ISSUE THREAD

**Issue by mpinch** [appcelerator/titanium_mobile#11381]
When switching to Titanium 8+, it has broken the OAuth redirection process inside of a Titanium App when using the new implementation of WebView.  The same web based OAuth process works fine on iOS 13 Safari, as well as in a native implementation of an iOS app using WKWebview.  

This failure is demonstrated below using the ADP Workforce now Authentication process, and it errors out with a -999 error.  There is little documentation on this, and ideally, I'd just like a way to allow Titanium to log the error but not stop the redirection process.  If you go to https://app.snapeval.com/user and click login with adp, you can see the process i'm describing:

Logs show:

[INFO] :   beforeload{"url":"https://app.snapeval.com/ser/adp","navigationType":0,"bubbles":true,"type":"beforeload",

[INFO] :   beforeload{"url":"https://accounts.adp.com/auth/oauth/v2/authorize?response_type=code&client_id=4519a72a-296b-4a58-869a-80f75deb77a6&redirect_uri=https%3A%2F%2Fapp%2Esnapeval%2Ecom%2Fopenid-connect%2Fadp&scope=openid&state=ad46c3c7dd26349daca4189cb0c3c429",

[INFO] :   redirect{"url":"https://accounts.adp.com/auth/oauth/v2/authorize?response_type=code&client_id=4519a72a-296b-4a58-869a-80f75deb77a6&redirect_uri=https%3A%2F%2Fapp%2Esnapeval%2Ecom%2Fopenid-connect%2Fadp&scope=openid&state=ad46c3c7dd26349daca4189cb0c3c429",

[INFO] :   error{"success":false,"code":-999,"url":"https://app.snapeval.com/user/","error":"cancelled","bubbles":true,"type":"error",

**Comment by ewanharris** [comment]
Closing due to age, please ensure to include some form of code or sample project that helps to diagnose the issue
