### ISSUE TITLE
WebViewer Not Displaying PDF's on Android

### ISSUE THREAD

**Issue by jny986** [appcelerator/titanium_mobile#11422]
I have an issue with our app where if a web hosted PDF is linked to in the app clicking on the link results in a general error:

![Screenshot_20200109-114041](https://user-images.githubusercontent.com/37679074/72029245-3cefe900-32d5-11ea-86a7-586a8ad51e70.png)

The link works fine on iOS but not android

If someone could help with fixing this issue that would be appreciated. 

**Describe the bug**
Failing to load PDF in web viewer for Android

**To Reproduce**
1. Create a text link to a pdf file hosted on a web server
2. Click on the link to view it

**Expected behavior**
Display the PDF embedded into the browser or download and open in local app

**Environment**
Titanium SDK version: 8.3.0.GA
CLI version: 7.1.2

**Comment by m1ga** [comment]
the Android webview is not able to open PDF files. You have to add something like pdf.js (https://github.com/m1ga/ti-pdf-js), use this module https://github.com/SquirrelMobile/pdfview or use and intent/openurl to open the pdf in an external PDF app (https://www.tidev.io/2014/04/18/adding-a-pdf-reader-to-your-android-app/)
