### ISSUE TITLE
Android: no `delete` event in ListView/TableView

### ISSUE THREAD

**Issue by m1ga** [appcelerator/titanium_mobile#12626]
### Describe the bug
In https://github.com/appcelerator/titanium_mobile/pull/12298 the `delete` event was added to Android. While it looks and works fine I don't get any event after the item was deleted. There is a `delete` event on iOS which should fire on Android, too.

Adding this:

https://github.com/appcelerator/titanium_mobile/blob/master/android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/ListViewProxy.java#L159

```
final KrollDict data = new KrollDict();
data.put(TiC.PROPERTY_SECTION_INDEX, getIndexOfSection(section));
data.put(TiC.PROPERTY_ITEM_INDEX, index);
fireEvent(TiC.EVENT_DELETE, data);
```

https://github.com/appcelerator/titanium_mobile/blob/master/android/modules/ui/src/java/ti/modules/titanium/ui/TableViewProxy.java#L230
```
final KrollDict data = new KrollDict();
data.put(TiC.PROPERTY_INDEX, adapterIndex);
fireEvent(TiC.EVENT_DELETE, data);
```

works fine but I can't read the event item with
```
$.listview.sections[e.sectionIndex].getItemAt(e.itemIndex).properties.id;
```
because it is gone already. Not sure how iOS does this at the moment. But at least knowing which item was deleted so I can remove it from a DB would be fine :smile: 

### To Reproduce
Use the code from https://github.com/appcelerator/titanium_mobile/pull/12298 and add the `delete` event to the listview. It won't fire.

### Expected behavior
`delete` should fire and it would be great to get the properties of the deleted item (e.g. an attached ID).

### Environment
Titanium SDK version: 9.3.2.GA, 10.1.0

**Comment by jquick-axway** [comment]
@m1ga , thanks for the feedback.
A ticket was written for this here: [TIMOB-28402](https://jira.appcelerator.org/browse/TIMOB-28402)
