### ISSUE TITLE
Titanium SDK 9.3.2GA- iOS 14 packaging error

### ISSUE THREAD

**Issue by arunraj-qburst** [appcelerator/titanium_mobile#12789]
### Describe the bug

Hi,
I was trying to take a package for Appstore release with Titanium SDK 9.3.2GA with XCode 12. After compiling the javascritp code the console shows the below error message,

If using Appcelerator Studio,
`Error: <terminated> iOS iTunes Distribution [ my-app-name-here] Application packager`
if using VSCode:
```
[INFO]  Processing JavaScript files
[INFO]  Writing app properties
2021-05-09T16:30:26.937Z | ERROR  | An uncaught exception was thrown!
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
2021-05-09T16:30:26.937Z | ERROR  | The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
Process exited with 1
The terminal process terminated with exit code: 1.
```
I tried by providing all the permissions to XCode & Studio but still not succeeded.
The ironey is that I am still able to run the project in both Android & iOS emulators. There is no issues as such with run/ debug. But only with the packaging.
Can some one help me in this regard please ?

**System environment :**
OS : Mac BigSur 11.2.3

java -version
java version "15.0.2" 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)

node -v
v14.16.1

XCode : 12

ti -v
5.3.1

Titanium SDK 9.3.2GA

**Comment by m1ga** [comment]
there is already a PR for this: https://github.com/appcelerator/titanium_mobile/pull/12782
Either downgrade to node 12 or apply the fix to your local version

**Comment by ewanharris** [comment]
@m1ga is correct here, please downgrade to Node 12 or apply the fix in the associated PR
