### ISSUE TITLE
Webview loading temporary file on subsequent loads (iOS 14) TI SDK 9.3.2GA

### ISSUE THREAD

**Issue by arunraj-qburst** [appcelerator/titanium_mobile#12823]
### Describe the bug
When ever I am trying to load the same webpage url, the page is not getting loaded (only iOS)
The webview event "BEFORELOAD" triggering two times and it is loading from a temporary location as given below,
`URL: file:///Users/arunrajsaraswathy/Library/Developer/CoreSimulator/Devices/CF75944B-1866-40D5-98EB-94155704409E/data/Containers/Bundle/Application/E0AA006C-0767-48A9-8DE1-559A7D34B9E4/<<my-app-name-here>>.app/`
Actual URL set:
`https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/launch-screen/`
Note: this is happening only with iOS, but working fine with Android
No errors are triggering 
### To Reproduce
Load webview multiple time with same URL
 

### Expected behavior
Should load the webpage every time I set the url to the webview instance

### Environment
Titanium SDK version: 9.3.2GA
CLI version:8.1 .1
XCode Ver: 12
iOS ver : 14++
### Logs
 `URL: file:///Users/arunrajsaraswathy/Library/Developer/CoreSimulator/Devices/CF75944B-1866-40D5-98EB-94155704409E/data/Containers/Bundle/Application/E0AA006C-0767-48A9-8DE1-559A7D34B9E4/<<my-app-name-here>>.app/`

**Comment by m1ga** [comment]
again some code would be very helpful
```
var window = Ti.UI.createWindow();
var ww = Ti.UI.createWebView({
  url: "https://www.unixtime.de/"
});
var btn = Ti.UI.createButton({
  title:" reload ",
  backgroundColor:"#aaa"
});
btn.addEventListener("click",function(){
  ww.url = "https://www.unixtime.de/"
})
window.add(ww);
window.add(btn);
window.open();
```
works fine. It will display a new time in the dropdowns everytime you click reload.

A workaround for you if there is just a caching problem: add a random number as a GET parameter at the end. Then it should be a new URL

**Comment by ewanharris** [comment]
Same as m1ga I cannot reproduce this issue.

If this issue still persists for you, please file a new issue with a minimal code sample that demonstrates the issue
