### ISSUE TITLE
Specifying MAP_TYPE_NORMAL on Ti.Map in Android causes a "null" error crash

### ISSUE THREAD

**Issue by jasonkneen** [appcelerator/titanium_mobile#13056]
1. Create a new instance of Ti.Map on Android
2. Create a view and specify `mapType: maps.MAP_TYPE_NORMAL`
3. Build the app

On iOS it's fine, on Android the app crashes complaining about a null value -- removing this solves it but there should be parity between iOS and Android if we're sharing code.

**Comment by m1ga** [comment]
I think iOS is the problem and should complain too :wink: 

It should be `mapType: Map.NORMAL_TYPE`
Android: https://github.com/appcelerator-modules/ti.map/blob/b52163aa72161c5bcefc757ae4206a583d6f5c64/android/src/ti/map/MapModule.java#L79
iOS: https://github.com/appcelerator-modules/ti.map/blob/01d22c13e84034e3d86e83e2566517d48d7d58ca/ios/Classes/TiMapModule.h#L15

https://titaniumsdk.com/api/modules/map.html#constants
(can't link to ` NORMAL_TYPE` directly)

**Comment by jasonkneen** [comment]
Ahh, looks like lifted old code from somewhere else -- that could explain it -- iOS didn't crash but just ignored it I guess. Thanks!
