### ISSUE TITLE
barColor and tintColor does not work on window.setToolbar iOS 15

### ISSUE THREAD

**Issue by Oxnap** [appcelerator/titanium_mobile#13164]
### Describe the bug
If I try to execute the .setToolbar method on a iOS 15 simulator or device, the barColor and tintColor does not work. If the window have a color, the toolbar uses this color, but not a specified one.
It only happens on iOS 15. In other versions it works as should

### To Reproduce
Steps to reproduce the behavior, e.g.:
1. Create new project
2. Add a NavigationWindow with a window inside it.
3. Edit the doClick function and add the 
$.win.setToolbar($.UI.create('Button', {color}), {animated: true, barColor: 'red'});
4. The toolbar shows the blue button on a white background.

### Expected behavior
The toolbar should have the specified color.

### Environment
Titanium SDK version: 10.1.0.GA
CLI version: 9.0.1
xCode 13.1 with iPad  iOS 15 Simulator

### Logs

<img width="965" alt="Captura de Pantalla 2021-11-03 a la(s) 19 02 49" src="https://user-images.githubusercontent.com/15158592/140199449-893be0dc-7e0c-4b06-a0e4-4df30b196edc.png">

![Captura de Pantalla 2021-11-03 a la(s) 19 04 04](https://user-images.githubusercontent.com/15158592/140199582-c2e1f6af-b3dd-4c90-a441-b4cb56000fe5.png)

**Comment by jquick-axway** [comment]
I can't reproduce the "tintColor" issue on iOS 15 with the toolbar... but I can reproduce the toolbar "barColor" issue. The real issue here is that the toolbar is always transparent on iOS 15. Even if you don't set the toolbar "barColor", it's supposed to default to gray like the top navigation bar.

```javascript
let navigationWindow = null;
const rootWindow = Ti.UI.createWindow({
	barColor: "orange",
	backgroundColor: "yellow",
	title: "Test App",
});
const button1 = Ti.UI.createButton({
	title: "Button 1",
	color: "red",
});
button1.addEventListener("click", () => { alert("Clicked: Button 1"); });
const button2 = Ti.UI.createButton({
	title: "Button 2",
});
button2.addEventListener("click", () => { alert("Clicked: Button 2"); });
rootWindow.setToolbar([button1, button2], {
	animated: true,
	barColor: "orange",  // <- Ignored on iOS 15.
	tintColor: "purple",
});
rootWindow.add(Ti.UI.createLabel({ text: "iOS setToolBar() Test" }));
rootWindow.open();
navigationWindow = Ti.UI.createNavigationWindow({
	window: rootWindow,
});
navigationWindow.open();
```

**Comment by jquick-axway** [comment]
I wrote up a ticket for this issue here.
https://jira.appcelerator.org/browse/TIMOB-28574

**Comment by jquick-axway** [comment]
PR #13165 fixes the issue.
