### ISSUE TITLE
Android. ScrollView. NullPointerException

### ISSUE THREAD

**Issue by drauggres** [appcelerator/titanium_mobile#13196]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.appcelerator.titanium.proxy.TiViewProxy.hierarchyHasListener(java.lang.String)' on a null object reference
  at ti.modules.titanium.ui.widget.TiUIScrollView$TiScrollViewLayout$1.onSingleTapConfirmed(TiUIScrollView.java:82)
  at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:331)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:236)
  at android.app.ActivityThread.main(ActivityThread.java:7889)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

### Expected Behavior

Need to add if (this.proxy == null) return; guards to the "`SimpleOnGestureListener`"s methods inside of `TiUIScrollView` class.

### Actual behavior

App crash

### Reproducible sample

--

### Steps to reproduce

--

### Platform

Android

### SDK version you are using

9.2.2 (should be reproducible on the `master`)

**Comment by m1ga** [comment]
https://github.com/appcelerator/titanium_mobile/pull/13199
The line numbers don't match 9.2.x or master but I've added a check where it wants to use the proxy

**Comment by drauggres** [comment]
> #13199 The line numbers don't match 9.2.x or master

https://github.com/appcelerator/titanium_mobile/blob/9_2_X/android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollView.java#L82

> I've added a check where it wants to use the proxy

Thank you, I was going to fix this myself (someday, maybe ...)

**Comment by m1ga** [comment]
> https://github.com/appcelerator/titanium_mobile/blob/9_2_X/android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollView.java#L82

Strange :thinking: I thought I've switched the branch too

**Comment by drauggres** [comment]
Actually, it'is the other issue (#13195) that don't match line number with 9_2_x. But you added `if` to the right place (though, I would add `if (proxy == null) return;`  right to the top of the method).
